# Generated by Django 5.0.4 on 2024-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_medicamento', models.ImageField(blank=True, max_length=255, upload_to='images/medicamentos/')),
                ('nome', models.CharField(max_length=100)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('apresentacao', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('composicao', models.CharField(max_length=50)),
                ('posologia_recomendada', models.CharField(max_length=50)),
                ('nome_substancia', models.CharField(max_length=50)),
            ],
        ),
    ]
