# Generated by Django 5.0.4 on 2024-08-29 17:48

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('foto_perfil', models.ImageField(blank=True, max_length=255, upload_to='images/medicos/')),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=10)),
                ('especialidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital_clinica', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
