# Generated by Django 5.0.4 on 2024-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/'),
        ),
    ]
