# Generated by Django 5.0.4 on 2024-08-29 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cids', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons_medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=20)),
                ('periodicidade', models.CharField(max_length=40)),
                ('tempo_de_uso_dias', models.IntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('pressao', models.CharField(max_length=7)),
                ('glicose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_cardiaca', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sat_oxigenio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacoes', models.TextField()),
                ('cids', models.ManyToManyField(to='cids.cid')),
                ('medicamentos', models.ManyToManyField(through='consultas.Cons_medicamento', to='medicamentos.medicamento')),
            ],
        ),
    ]
