# Generated by Django 5.0.4 on 2024-09-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cons_medicamento',
            name='dose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cons_medicamento',
            name='periodicidade',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cons_medicamento',
            name='tempo_de_uso_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
