# Generated by Django 5.0.4 on 2024-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
