# Generated by Django 5.0.4 on 2024-08-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cid',
            name='nome',
        ),
    ]
